config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'
  get 'myprofile' => 'dashboard#edit_profile'

  resources :clients
  resources :staffs
  resources :task_logs
  devise_for :users, :path_prefix => 'profiles'
  resources :users
  root 'pages#home'

end

app/models/staff.rb
class Staff < ActiveRecord::Base

	has_one :user, as: :meta, dependent: :destroy
	accepts_nested_attributes_for :user, :update_only => true

	has_many :task_logs

	has_many :employments
	has_many :clients, :through => :employments
	accepts_nested_attributes_for :employments, allow_destroy: true

	def total_time_today
	end
	def total_time_week
	end
	def total_time_month
	end
	def total_staff_time
		"#{full_name}"
		# today = Date.today
    	# hrs_all_time = TaskLog.joins(:client).select("clients.*, SUM(task_logs.total_hrs) AS all_time").group("today").where(user_id: current_user)
	end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /staffs
  # GET /staffs.json
  def index
    if current_user.role == 'admin'
    @staffs = Staff.all
    @task_logs = TaskLog.all

    @task_logs_by_date = @task_logs.group_by { |c| c.created_at.to_date }
    elsif current_user.role == 'manager'
    @staffs = Staff.all
    @task_logs = TaskLog.all

    @task_logs_by_date = @task_logs.group_by { |c| c.created_at.to_date }
    elsif current_user.role == 'team_leader'
        redirect_to dashboard_path
    elsif current_user.role == 'client'
        redirect_to dashboard_path
    else
      redirect_to dashboard_path
    end
    

  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    if current_user.role == 'admin'
      @staff = Staff.new
    elsif current_user.role == 'manager'
      @staff = Staff.new
    elsif current_user.role == 'team_leader'
        redirect_to dashboard_path
    elsif current_user.role == 'client'
        redirect_to dashboard_path
    else
      redirect_to dashboard_path
    end
    @name = current_user.meta.full_name.split(" ").map { |s| s.to_s }
    @first_name = "#{@name[0].to_s}"
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(update_staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:full_name, :position, user_attributes: [ :id, :email, :password , :role])
    end
    
    def update_staff_params
      params.require(:staff).permit(:full_name, :position, user_attributes: [ :id , :role], client_ids:[])
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
  # Returns the Gravatar for the given user.
    def gravatar_for(user, options = { size: 80 })
      gravatar_id = Digest::MD5.hexdigest(staff.user.email.downcase)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      image_tag(gravatar_url, alt: user.full_name, class: "gravatar img-responsive img-thumbnail img-circle")
    end
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit 'Add Staff' %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<% provide(:title, 'Editing Staff') %>
<% content_for :body_class, 'theme-silver main-menu-animated dont-animate-mm-content-sm animate-mm-md animate-mm-lg' %>
<% content_for :main_wrapper, 'main-wrapper' %>
<h1>Editing Staff</h1>

<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :user_attributes, @staff.user do |ff| %>
  <div class="field">
      <%= ff.label :role %><br />
      <%= ff.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
<%= hidden_field_tag "staff[client_ids][]", nil %>
<% Client.all.each do |client| %>
  <%= check_box_tag "staff[client_ids][]", client.id, @staff.client_ids.include?(client.id), id: dom_id(client) %>
  <%= label_tag dom_id(client), client.full_name %><br>
<% end %>
<br>
  <div class="actions">
    <%= f.submit 'Edit Staff' %>
  </div>
<% end %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Staffs</h1>
<p><%= link_to 'New Staff', new_staff_path, class: 'btn btn-success', :role => 'button' %></p>
<div id="no-more-tables">
<table class="col-md-12 table-bordered table-striped table-condensed cf">
  <thead class="cf">
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Postion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td data-title="Name"><%= staff.full_name %></td>
        <td data-title="Email"><%= staff.user.email %></td>
        <td data-title="Role"><%= staff.user.role.humanize %></td>
        <td data-title="Position"><%= staff.position %></td>
        <td data-title="Show"><%= link_to 'Show', staff %></td>
        <td data-title="Edit"><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td data-title="Delete"><%= link_to 'Delete', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br/>

app/views/staffs/new.html.erb
<% content_for :body_class, 'theme-silver main-menu-animated dont-animate-mm-content-sm animate-mm-md animate-mm-lg' %>
<% content_for :main_wrapper, 'main-wrapper' %>
<% provide(:title, 'Add Staff') %>
<div class="panel form-horizontal">
<div class="panel-heading">
            <span class="panel-title">Add Staff</span>
</div>
<%= form_for(@staff) do |f| %>
<div class="panel-body">
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :user_attributes, @staff.user||User.new do |ff| %>
  <div class="form-group">
      <%= ff.label :role, class: "col-sm-2 control-label" %>
      <div class="col-sm-10 ">
        <%= ff.select(:role, User.roles.keys.map {|role| [role.titleize,role]}, :class => 'form-control form-group-margin') %>
      </div>
      
  </div>
    <div class="form-group">
    <%= ff.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= ff.email_field :email, autofocus: true, class: "form-control", placeholder: "Email" %>
    </div>
    </div>
    <div class="form-group">
      <%= ff.label :password, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
      <%= ff.text_field :password, class: "form-control", placeholder: "Password" %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :full_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.text_field :full_name, class: "form-control", placeholder: "Full Name" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :position, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.text_field :position, class: "form-control", placeholder: "Position" %>
    </div>
  </div>
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit value: "Add New Staff", class: "btn btn-primary" %>
  </div>
</div>
<% end %>
</div>

app/views/staffs/show.html.erb
<% provide(:title, 'My Profile') %>
<% content_for :body_class, 'theme-silver main-menu-animated dont-animate-mm-content-sm page-profile animate-mm-md animate-mm-lg' %>
<% content_for :main_wrapper, 'main-wrapper' %>
<div class="profile-full-name"> <span class="text-semibold"><%= @staff.full_name %></span>'s profile </div>
<div class="profile-row">
  <div class="left-col">
    <div class="profile-block">
      <div class="panel profile-photo"> <%= image_tag("http://gravatar.com/avatar/"+ Digest::MD5.hexdigest(current_user.email.downcase)+"?s=160", class: "rounded") %></div>
      <br>
      <a href="#" class="btn btn-success"><i class="fa fa-check"></i>&nbsp;&nbsp;Following</a>&nbsp;&nbsp; <a href="#" class="btn"><i class="fa fa-comment"></i></a> </div>
    <div class="panel panel-transparent">
      <div class="panel-heading"> <span class="panel-title">About me</span> </div>
      <div class="panel-body"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et <a href="#">dolore magna</a> aliqua. </div>
    </div>
    <div class="panel panel-transparent">
      <div class="panel-heading"> <span class="panel-title">Statistics</span> </div>
      <div class="list-group"> <a href="#" class="list-group-item"><strong>126</strong> Likes</a> <a href="#" class="list-group-item"><strong>579</strong> Followers</a> <a href="#" class="list-group-item"><strong>100</strong> Following</a> </div>
    </div>
    <div class="panel panel-transparent profile-skills">
      <div class="panel-heading"> <span class="panel-title">Skills</span> </div>
      <div class="panel-body"> <span class="label label-primary">UI/UX</span> <span class="label label-primary">Web design</span> <span class="label label-primary">Photoshop</span> <span class="label label-primary">HTML</span> <span class="label label-primary">CSS</span> </div>
    </div>
    <div class="panel panel-transparent">
      <div class="panel-heading"> <span class="panel-title">Social</span> </div>
      <div class="list-group"> <a href="#" class="list-group-item"><i class="profile-list-icon fa fa-twitter" style="color: #4ab6d5"></i> @dsteiner</a> <a href="#" class="list-group-item"><i class="profile-list-icon fa fa-facebook-square" style="color: #1a7ab9"></i> Denise Steiner</a> <a href="#" class="list-group-item"><i class="profile-list-icon fa fa-envelope" style="color: #888"></i> dsteiner@example.com</a> </div>
    </div>
  </div>
  <div class="right-col">
	<hr class="profile-content-hr no-grid-gutter-h">
<div class="profile-content">
					<ul id="profile-tabs" class="nav nav-tabs">
						<li class="active">
							<a href="#profile-tabs-board" data-toggle="tab">Profile</a>
						</li>
						<li>
							<a href="#profile-tabs-activity" data-toggle="tab">Timeline</a>
						</li>
						<li>
							<a href="#profile-tabs-followers" data-toggle="tab">Followers</a>
						</li>
						<li>
							<a href="#profile-tabs-following" data-toggle="tab">Following</a>
						</li>
					</ul>
<div class="tab-content tab-content-bordered panel-padding">
	<div class="widget-article-comments tab-pane panel no-padding no-border fade" id="profile-tabs-board">
<div class="panel colourable">
					<!-- Default panel contents -->
					<div class="panel-heading">
						<span class="panel-title">Client</span>
					</div>

					<!-- Table -->
					<table class="table">
						<thead>
							<tr>
								<th>#</th>
								<th>First Name</th>
								<th>Business Name</th>
							</tr>
						</thead>
						<tbody>
						<% @staff.clients.each do |client| %>
						<tr>
								<td><%= client.id %></td>
								<td><%= client.full_name %></td>
								<td><%= client.business_name %></td>
						</tr>
						<% end %>
						</tbody>
					</table>
				</div>
	</div>
	<div id="profile-tabs-activity" class="tab-pane fade panel ">
		dnsoje
	</div>
	<div id="profile-tabs-followers" class="tab-pane fade panel widget-followers">
		np[efn]
	</div>
	<div id="profile-tabs-following" class="tab-pane fade panel widget-followers">
		jeo dioe
	</div>
</div>
</div>
  </div>
</div>