config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'
  get 'myprofile' => 'dashboard#edit_profile'

  resources :clients
  resources :staffs
  resources :task_logs
  devise_for :users, :path_prefix => 'profiles'
  resources :users
  root 'pages#home'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :set_dashboard, only: [:index, :edit_profile]
	# before_action :set_client_dashboard, only: [:index]

  def index
  	@users = User.all
    @staffs = Staff.all
    @clients = Client.all
    @task_logs = TaskLog.all

    @task_logs_by_date = @task_logs.group_by { |c| c.created_at.to_date }

    @date = params[:date] ? Date.parse(params[:date]) : Date.today

    @today = Date.today
    @total_time_today = TaskLog.joins(:client).select("clients.*, SUM(task_logs.total_hrs) AS time_today").group("@today").where(user_id: current_user)

    @hrs_all_time = TaskLog.joins(:client).select("clients.*, SUM(task_logs.total_hrs) AS all_time").group("@today").where(user_id: current_user)

    @hrs_by_client = TaskLog.joins(:client).select("clients.*, SUM(task_logs.total_hrs) AS hrs_this_month").group("clients.id").where(user_id: current_user)

    @hrs_by_staff = TaskLog.joins(:staff).joins(:client).joins(:user).select("staffs.full_name AS full_names").select("staffs.position AS positions").select("users.email AS emails").group("staffs.id").where(user_id: current_user)

    @name = current_user.meta.full_name.split(" ").map { |s| s.to_s }
    @first_name = "#{@name[0].to_s}"


    @dates = DateTime.now.utc
    @time_today = TaskLog.where('created_at >= ? and created_at <= ?', @dates.beginning_of_day, @dates.end_of_day).where(user_id: current_user).sum('total_hrs')
    @by_day = ("%.2f" % @time_today).to_s.split(".").map { |s| s.to_i }
    @total_today = @by_day[0].to_s + ":" + ((@by_day[1]*60)/100).to_s + " Hrs."


    @time_week = TaskLog.where('created_at >= ? and created_at <= ?', @dates.beginning_of_week(start_day = :monday), @dates.end_of_week(end_day = :sunday)).where(user_id: current_user).sum('total_hrs')
    @by_week = ("%.2f" % @time_week).to_s.split(".").map { |s| s.to_i }
    @total_week = @by_week[0].to_s + ":" + ((@by_week[1]*60)/100).to_s + " Hrs."


    @time_month = TaskLog.where('created_at >= ? and created_at <= ?', @dates.beginning_of_month, @dates.end_of_month).where(user_id: current_user).sum('total_hrs')
    @by_month = ("%.2f" % @time_month).to_s.split(".").map { |s| s.to_i }
    @total_month = @by_month[0].to_s + ":" + ((@by_month[1]*60)/100).to_s + " Hrs."

  end

  def edit_profile
  	@users = User.all
    @staffs = Staff.all
    @clients = Client.all
    @task_logs = TaskLog.all
  end

  private
    def set_dashboard
    	if  current_user.role == 'staff'
    		@staff = Staff.find(current_user.meta.id)
    	elsif current_user.role == 'client'
    		@client = Client.find(current_user.meta.id)
    	end
      
    end

end

app/helpers/dashboard_helper.rb
module DashboardHelper

# def my_helper
#     total_hrs_by_date.each do |client|
#       # content_tag(:tr)
#       # content_tag(:td, :data => {:title => "Name" }) + client.full_name
#       # content_tag(:td, :data => {:title => "Business Name" }) client.business_name
#       # content_tag(:td, :data => {:title => "Total Time" })
#       # c = ("%.2f" % client.hrs_this_month).to_s.split(".").map { |s| s.to_i }
#       # a = c[0].to_s + ":" + ((c[1]*60)/100).to_s + " Hrs."
#     end
#   end
#   def mhsn
#   	arr = ["a", "b", "c"]
#   		content_tag(:tr) do
#   		  arr.each do |item|
#   		  concat content_tag(:td, item)
#   		end
#   	end
#   end

end

app/views/dashboard/index.html.erb
<% provide(:title, 'Dashboard') %>
<% content_for :body_class, 'theme-silver main-menu-animated dont-animate-mm-content-sm animate-mm-md animate-mm-lg' %>
<% content_for :main_wrapper, 'main-wrapper' %>
<% if current_user.role == 'admin' %>

<p><%= link_to 'Add New Staff', new_staff_path, class: 'btn btn-success', :role => 'button' %></p>
<div class="panel panel-dark panel-light-green table-light">
  <div class="panel-heading"><span class="panel-title">All Staffs</span></div>
  <table class="table table-bordered">
    <thead class="cf">
      <tr>
        <th rowspan="2">Full name</th>
        <th rowspan="2">Email</th>
        <th rowspan="2">Role</th>
        <th rowspan="2">Number of client</th>
        <th rowspan="2">Postion</th>
        <th colspan="4">Total work hour</th>
        <th colspan="3" rowspan="2"></th>
      </tr>
      <tr>
        <th>Today</th>
        <th>Week</th>
        <th>Month</th>
        <th>All Time</th>
      </tr>
    </thead>
    <tbody>
      <% @staffs.each do |staff| %>
      <tr>
        <td data-title="Name"><%= image_tag("http://gravatar.com/avatar/"+ Digest::MD5.hexdigest(staff.user.email.downcase)+"?s=26", class: "rounded") %> <%= staff.full_name %></td>
        <td data-title="Email"><%= staff.user.email %></td>
        <td data-title="Role"><%= staff.user.role.humanize %></td>
        <td data-title="Role"><%= staff.clients.count %></td>
        <td data-title="Position"><%= staff.position %></td>
        <td data-title="Number of hrs today"></td>
        <td data-title="Number of hours this week"></td>
        <td data-title="Number of hours this month"></td>
        <td data-title="All time Number of hrs"></td>
        <td data-title="Show"><%= link_to 'Show', staff %></td>
        <td data-title="Edit"><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td data-title="Delete"><%= link_to 'Delete', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<p><%= link_to 'Add New Client', new_client_path, class: 'btn btn-success', :role => 'button' %></p>
<div class="panel panel-dark panel-light-green table-light">
  <div class="panel-heading"><span class="panel-title">All Clients</span></div>
  <table class="table table-bordered">
    <thead class="cf">
      <tr>
        <th>Full name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Number of staff</th>
        <th>Business Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
      <tr>
        <td data-title="Name"><%= image_tag("http://gravatar.com/avatar/"+ Digest::MD5.hexdigest(client.user.email.downcase)+"?s=26", class: "rounded") %> <%= client.full_name %></td>
        <td data-title="Email"><%= client.user.email %></td>
        <td data-title="Role"><%= client.user.role.humanize %></td>
        <td data-title="Role"><%= client.staffs.count %></td>
        <td data-title="Business Name"><%= client.business_name %></td>
        <td data-title="Show"><%= link_to 'Show', client %></td>
        <td data-title="Edit"><%= link_to 'Edit', edit_client_path(client) %></td>
        <td data-title="Delete"><%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% elsif current_user.role == 'manager' %>

<% elsif current_user.role == 'team_leader' %>

<div class="panel panel-dark panel-light-green table-light">
  <div class="panel-heading"><span class="panel-title">All Staffs</span></div>
  <table class="table table-bordered">
    <thead class="cf">
      <tr>
        <th rowspan="2">Full name</th>
        <th rowspan="2">Email</th>
        <th rowspan="2">Role</th>
        <th rowspan="2">Number of client</th>
        <th rowspan="2">Postion</th>
        <th colspan="4">Total work hour</th>
      </tr>
      <tr>
        <th>Today</th>
        <th>Week</th>
        <th>Month</th>
        <th>All Time</th>
      </tr>
    </thead>
    <tbody>
      <% @staffs.each do |staff| %>
      <tr>
        <td data-title="Name"><%= image_tag("http://gravatar.com/avatar/"+ Digest::MD5.hexdigest(staff.user.email.downcase)+"?s=26", class: "rounded") %> <%= staff.full_name %></td>
        <td data-title="Email"><%= staff.user.email %></td>
        <td data-title="Role"><%= staff.user.role.humanize %></td>
        <td data-title="Role"><%= staff.clients.count %></td>
        <td data-title="Position"><%= staff.position %></td>
        <td data-title="Number of hrs today"></td>
        <td data-title="Number of hours this week"></td>
        <td data-title="Number of hours this month"></td>
        <td data-title="All time Number of hrs"></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="panel panel-dark panel-light-green table-light">
  <div class="panel-heading"><span class="panel-title">All Clients</span></div>
  <table class="table table-bordered">
    <thead class="cf">
      <tr>
        <th>Full name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Number of staff</th>
        <th>Business Name</th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
      <tr>
        <td data-title="Name"><%= image_tag("http://gravatar.com/avatar/"+ Digest::MD5.hexdigest(client.user.email.downcase)+"?s=26", class: "rounded") %> <%= client.full_name %></td>
        <td data-title="Email"><%= client.user.email %></td>
        <td data-title="Role"><%= client.user.role.humanize %></td>
        <td data-title="Role"><%= client.staffs.count %></td>
        <td data-title="Business Name"><%= client.business_name %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% elsif current_user.role == 'client' %>
<div class="panel panel-dark panel-light-green">
  <div class="panel-heading"><span class="panel-title">My Staff</span></div>
  <table class="table table-bordered">
    <tr>
      <th rowspan="2">Full name</th>
      <th rowspan="2">Postion</th>
      <th colspan="3">Time</th>
    </tr>
    <tr>
      <th>Today</th>
      <th>Week</th>
      <th>Month</th>
    </tr>
      </thead>
    
    <tbody>
      <% @hrs_by_staff.each do |staff| %>
      <tr>
        <td data-title="Name"><%= image_tag("http://gravatar.com/avatar/"+ Digest::MD5.hexdigest(staff.emails.downcase)+"?s=26", class: "rounded") %> <%= staff.full_names %></td>
        <td data-title="Position"><%= staff.positions %></td>
        <td data-title="Today"></td>
        <td data-title="Week"></td>
        <td data-title="Month"></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
<div class="panel panel-dark panel-light-green">
  <div class="panel-heading"><span class="panel-title">Timeline</span></div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Time Worked Today</th>
        <th>Time Worked This Week</th>
        <th>Time Worked This Month</th>
        <th>All Time</th>
      </tr>
    </thead>
    <tbody class="valign-middle">
      <tr>
        <td data-title="Today"><%= @total_today %></td>
        <td data-title="Week"><%= @total_week %></td>
        <td data-title="Months"><%= @total_month %></td>
        <td data-title="All Time"><% @total_time_today.each do |client|%><%= c = ("%.2f" % client.time_today).to_s.split(".").map { |s| s.to_i }
            a = c[0].to_s + ":" + ((c[1]*60)/100).to_s + " Hrs."

             %><% end %></td>
      </tr>
    </tbody>
  </table>
</div>
<div class="panel panel-dark panel-light-green">
  <div class="panel-heading"><span class="panel-title">My Client</span></div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Full name</th>
        <th>Business Name</th>
        <th>Time</th>
      </tr>
    </thead>
    <tbody class="valign-middle">
      <% @hrs_by_client.each do |client|%>
      <tr>
        <td data-title="Name"><%= client.full_name %></td>
        <td data-title="Business Name"><%= client.business_name %></td>
        <td data-title="Month"><%= c = ("%.2f" % client.hrs_this_month).to_s.split(".").map { |s| s.to_i }
            a = c[0].to_s + ":" + ((c[1]*60)/100).to_s + " Hrs."

             %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div id="tasks_logs" class="panel panel-dark panel-light-green">
  <div class="panel-heading">
    <h2 id="month"><%= link_to date: @date.prev_month do %><i class="menu-icon fa fa-arrow-left"></i> < <% end %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to date: @date.next_month do %><i class="menu-icon fa fa-arrow-right"></i><% end %></h2>
  </div>
  <%= calendar @date do |date| %>
    <%= date.day %>
      <% if @task_logs_by_date[date] %>
        <ul class="list-group">
          <% @task_logs_by_date[date].each do |task_log| %>
            <%= @hrs_by_day %>
            <% if task_log.user == current_user %>
              <li class="list-group-item">
                <%= task_log.task_title %>
              </li>
            <% end %>
          <% end %>
        </ul>
      <% end %>
    <% end %>
</div>

<% end %>

<% content_for :body_init_js do %>
<!-- Pixel Admin's javascripts --> 
<script type="text/javascript">
  init.push(function () {
    // Javascript code here
  })
  window.PixelAdmin.start(init);
</script>
<% end %>