config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'
  get 'myprofile' => 'dashboard#edit_profile'

  resources :clients
  resources :staffs
  resources :task_logs
  devise_for :users, :path_prefix => 'profiles'
  resources :users
  root 'pages#home'

end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
<div id="main-navbar" class="navbar navbar-inverse" role="navigation"> 
    <!-- Main menu toggle -->
    <button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span></button>
    <div class="navbar-inner"> 
      <!-- Main navbar header -->
      <div class="navbar-header"> 
        
        <!-- Logo --> 
        <a href="index.html" class="navbar-brand">
        <div><%= image_tag("pixel-admin/main-navbar-logo.png", alt: "BossDash") %></div>
        BossDash </a> 
        
        <!-- Main navbar toggle -->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>
      </div>
      <!-- / .navbar-header -->
      
      <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
        <div>
          <div class="right clearfix">
            <ul class="nav navbar-nav pull-right right-navbar-nav">
              <li class="dropdown"> <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown"> <%= gravatar_for @user, size: 26 %> <span><%= current_user.meta.full_name %></span> </a>
                <ul class="dropdown-menu">
                  <li><%= link_to myprofile_path do %> Profile <% end %></li>
                  <li><a href="#"><span class="badge badge-primary pull-right">New</span>Account</a></li>
                  <li><a href="#"><i class="dropdown-icon fa fa-cog"></i>&nbsp;&nbsp;Settings</a></li>
                  <li class="divider"></li>
                  <li><%= link_to destroy_user_session_path, method: :delete do %><i class="dropdown-icon fa fa-power-off"></i> Log Out <% end %></li>
                </ul>
              </li>
            </ul>
            <!-- / .navbar-nav --> 
          </div>
          <!-- / .right --> 
        </div>
      </div>
      <!-- / #main-navbar-collapse --> 
    </div>
    <!-- / .navbar-inner --> 
  </div>
  <!-- / #main-navbar -->
  <% end %>

app/views/layouts/_left_sidebar.html.erb
  <div id="main-menu" role="navigation">
    <div id="main-menu-inner">
      <div class="menu-content top" id="menu-content-demo"> 
        <div>
          <div class="text-bg"><span class="text-slim">Welcome,</span> <span class="text-semibold"><%= @first_name %></span></div>
          <%= gravatar_for @user, size: 54 %>
          <div class="btn-group"><a href="#" class="btn btn-xs btn-primary btn-outline dark"><i class="fa fa-envelope"></i></a>
            <%= link_to myprofile_path, class: "btn btn-xs btn-primary btn-outline dark" do %><i class="fa fa-user"></i><% end %>
            <a href="#" class="btn btn-xs btn-primary btn-outline dark"><i class="fa fa-cog"></i></a>
            <%= link_to destroy_user_session_path, method: :delete, class: "btn btn-xs btn-danger btn-outline dark" do %><i class="fa fa-power-off"></i><% end %>
          </div>
          <a href="#" class="close">&times;</a>
        </div>
      </div>
      <ul class="navigation">
        <% if current_user.role == 'admin' %>
            <li> <%= link_to dashboard_path do %><i class="menu-icon fa fa-dashboard"></i><span class="mm-text">Dashboard</span><% end %> </li>
            <li><%= link_to new_staff_path do %><i class="menu-icon fa fa-user"></i><span class="mm-text">Add New Staff</span><% end %></li>
            <li><%= link_to new_client_path do %><i class="menu-icon fa fa-group"></i><span class="mm-text">Add New Client</span><% end %></li>
            <li><%= link_to task_logs_path do %><i class="menu-icon fa fa-calendar-check-o"></i><span class="mm-text">All Task</span><% end %></li>
            <li><%= link_to new_task_log_path do %><i class="menu-icon fa fa-calendar-plus-o"></i><span class="mm-text">Add new task</span><% end %></li>
        <% elsif current_user.role == 'manager' %>
            <li> <%= link_to dashboard_path do %><i class="menu-icon fa fa-dashboard"></i><span class="mm-text">Dashboard</span><% end %> </li>
            <li><%= link_to new_staff_path do %><i class="menu-icon fa fa-user"></i><span class="mm-text">Add New Staff</span><% end %></li>
            <li><%= link_to new_client_path do %><i class="menu-icon fa fa-group"></i><span class="mm-text">Add New Client</span><% end %></li>
        <% elsif current_user.role == 'team_leader' %>
            <li> <%= link_to dashboard_path do %><i class="menu-icon fa fa-dashboard"></i><span class="mm-text">Dashboard</span><% end %> </li>
            <li><%= link_to task_logs_path do %><i class="menu-icon fa fa-calendar-check-o"></i><span class="mm-text">All Task</span><% end %></li>
        <% elsif current_user.role == 'client' %>
            <li> <%= link_to dashboard_path do %><i class="menu-icon fa fa-dashboard"></i><span class="mm-text">Dashboard</span><% end %> </li>
        <% else %>
            <li> <%= link_to dashboard_path do %><i class="menu-icon fa fa-dashboard"></i><span class="mm-text">Dashboard</span><% end %> </li>
            <li><%= link_to new_task_log_path do %><i class="menu-icon fa fa-calendar-plus-o"></i><span class="mm-text">Add new task</span><% end %></li>
        <% end %>
      </ul>
      <!-- / .navigation -->
    </div>
    <!-- / #main-menu-inner --> 
  </div>
  <!-- / #main-menu --> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="ie8"> <![endif]-->
<!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="gt-ie8 gt-ie9 not-ie"> <!--<![endif]-->
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!--[if lt IE 9]>
		<script src="/assets/ie.min.js"></script>
	<![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield :body_class %>">
<div id="<%= yield :main_wrapper %>">
	<% if user_signed_in? %>
	<%= render 'layouts/header' %>
	<%= render 'layouts/left_sidebar' %>

	<div id="content-wrapper">
		<%= yield %> 
	</div>
<div id="main-menu-bg"></div>
<% else %>
		<%= yield %> 
<% end %>
</div>


<!-- Get jQuery from Google CDN -->
<!--[if !IE]> -->
	<script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js">'+"<"+"/script>"); </script>
<!-- <![endif]-->
<!--[if lte IE 9]>
	<script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">'+"<"+"/script>"); </script>
<![endif]-->

</body>
</html>